# Generated by Django 4.2.27 on 2026-05-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted - Pending Routing'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAST_TRACK', 'Fast-Track Queue'), ('MANAGER_REVIEW', 'Manager Review'), ('ESCALATED', 'Finance Escalation'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('adjusted_trust_score', models.IntegerField(blank=True, null=True)),
                ('recommended_route', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('merchant_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('payment_mode', models.CharField(max_length=50)),
                ('project_cost_centre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('bank_reconciled', models.BooleanField(default=False)),
                ('anomaly_status', models.CharField(default='NORMAL', max_length=20)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expenses.expenseclaim')),
            ],
        ),
    ]
